### ISSUE TITLE
waaai crashes when trying to shorten url

### ISSUE THREAD

**Issue by lc-guy** [underr/waaai#1]
```
~ » waaai http://www.google.com                                                                                                                                                                                     apt-get@apt-get
/usr/lib/node_modules/waaai/waaai.js:14
      var link = response.body.data.url;
                                   ^
TypeError: Cannot read property 'url' of undefined
    at /usr/lib/node_modules/waaai/waaai.js:14:36
    at done (/usr/lib/node_modules/waaai/node_modules/needle/lib/needle.js:354:7)
    at PassThrough.<anonymous> (/usr/lib/node_modules/waaai/node_modules/needle/lib/needle.js:512:9)
    at PassThrough.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
------------------------------------------------------------
```

**Comment by underr** [comment]
It looks like API's address changed to HTTPS and I didn't even notice that it broke waaai. 

Thanks for noticing, it's fixed now (99be0b2faf907e18310f8f646adaf004172cf10d).
